In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,roc_curve,roc_auc_score,silhouette_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from statistics import mode
d=pd.read_csv('trafficaccident.csv')
d
df = d.drop([ 'Location_Easting_OSGR', 'Location_Northing_OSGR','Longitude','Latitude', 'Police_Force','Date','Local_Authority_(District)','Local_Authority_(Highway)','1st_Road_Class', '1st_Road_Number', 'Speed_limit','Junction_Detail', 'Junction_Control', '2nd_Road_Class','2nd_Road_Number', 'Pedestrian_Crossing-Human_Control','Pedestrian_Crossing-Physical_Facilities','Special_Conditions_at_Site', 'Carriageway_Hazards','Did_Police_Officer_Attend_Scene_of_Accident','Accident_Index','LSOA_of_Accident_Location','Urban_or_Rural_Area','Time'], axis=1)
df
tr=d['Urban_or_Rural_Area']



# x_train,x_test,y_train,y_test=train_test_split(df,tr,train_size=0.8)

# df


In [2]:
df['Weather_Conditions']=df['Weather_Conditions'].fillna(mode(df['Weather_Conditions']))
df['Road_Surface_Conditions']=df['Road_Surface_Conditions'].fillna(mode(df['Road_Surface_Conditions']))
df.isna().sum()

Accident_Severity          0
Number_of_Vehicles         0
Number_of_Casualties       0
Day_of_Week                0
Road_Type                  0
Light_Conditions           0
Weather_Conditions         0
Road_Surface_Conditions    0
Year                       0
dtype: int64

In [4]:
df['Light_Conditions']=LabelEncoder().fit_transform(df['Light_Conditions'])

df['Road_Type']=LabelEncoder().fit_transform(df['Road_Type'])
df

df['Weather_Conditions']=LabelEncoder().fit_transform(df['Weather_Conditions'])

df['Road_Surface_Conditions']=LabelEncoder().fit_transform(df['Road_Surface_Conditions'])

df



Accident_Severity  Number_of_Vehicles  Number_of_Casualties  \
0                      2                   1                     1   
1                      3                   1                     1   
2                      3                   2                     1   
3                      3                   1                     1   
4                      3                   1                     1   
5                      3                   2                     1   
6                      3                   2                     1   
7                      3                   1                     2   
8                      3                   2                     2   
9                      3                   2                     5   
10                     3                   1                     1   
11                     3                   2                     1   
12                     3                   1                     1   
13                     3                   2                     1   
14                     3                   1                     2   
15                     3                   1                     1   
16                     2                   2                     1   
17                     3                   2                     1   
18                     3                   2                     1   
19                     2                   1                     1   
20                     3                   1                     1   
21                     3                   2                     1   
22                     3                   2                     1   
23                     3                   2                     1   
24                     3                   2                     1   
25                     3                   1                     1   
26                     3                   2                     1   
27                     3                   2                     2   
28                     3                   2                     1   
29                     3                   2                     1   
...                  ...                 ...                   ...   
9972                   3                   1                     1   
9973                   3                   1                     1   
9974                   2                   2                     1   
9975                   3                   2                     1   
9976                   3                   2                     1   
9977                   3                   2                     1   
9978                   3                   2                     1   
9979                   3                   2                     1   
9980                   3                   2                     1   
9981                   3                   2                     2   
9982                   3                   1                     1   
9983                   3                   2                     1   
9984                   3                   1                     1   
9985                   3                   1                     1   
9986                   3                   1                     2   
9987                   3                   1                     1   
9988                   3                   1                     1   
9989                   3                   1                     1   
9990                   2                   2                     2   
9991                   3                   2                     1   
9992                   3                   2                     1   
9993                   3                   2                     1   
9994                   3                   2                     1   
9995                   3                   1                     1   
9996                   3                   2                     1   
9997             

In [10]:
from sklearn.cluster import KMeans,MiniBatchKMeans,DBSCAN,Birch

import numpy as np
Y=np.array((d['Urban_or_Rural_Area']))
Y=Y.reshape(-1,1)
X = df[['Accident_Severity','Number_of_Vehicles','Number_of_Casualties','Day_of_Week','Road_Type','Light_Conditions','Weather_Conditions','Road_Surface_Conditions','Year']].copy()


In [11]:
kmeans = KMeans(n_clusters=2, random_state=100)
kmeans.fit(X)
pr=kmeans.predict(X)
ac=accuracy_score(Y,pr)
si=silhouette_score(Y,pr)
print(pr)
print(ac)
print(si)

[0 1 1 ... 0 1 0]
0.8272345530893821
0.14083893771529316


In [12]:
bb=Birch(threshold=0.5, branching_factor=50, n_clusters=2, compute_labels=True, copy=True)
bb.fit(X)
pr4=bb.fit_predict(X)
ac4=accuracy_score(Y,pr)
si4=silhouette_score(Y,pr)
print(pr4)
print(ac4)
print(si4)


C:\Users\gnara\Anaconda3\lib\site-packages\sklearn\utils\validation.py:179: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < '0.12':
C:\Users\gnara\Anaconda3\lib\site-packages\sklearn\utils\validation.py:179: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < '0.12':


[0 1 1 ... 0 1 0]
0.8272345530893821
0.14083893771529316


In [13]:
db=DBSCAN(eps=0.5, min_samples=2, metric='euclidean',leaf_size=10)
db.fit(X)
pr2=db.fit_predict(X,sample_weight=None)
ac2=accuracy_score(Y,pr)
si2=silhouette_score(Y,pr)
print(pr2)
print(ac2)
print(si2)

C:\Users\gnara\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):
C:\Users\gnara\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):
C:\Users\gnara\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):
C:\Users\gnara\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):


[  0   1   2 ...  49  30 197]
0.8272345530893821
0.14083893771529316


In [15]:
mn=MiniBatchKMeans(n_clusters=2, max_iter=100, batch_size=1024, verbose=0, compute_labels=True, random_state=10, tol=0.0, max_no_improvement=10)
mn.fit(X)
pr3=mn.predict(X,sample_weight=None)
ac3=accuracy_score(Y,pr)
si3=silhouette_score(Y,pr)
print(pr3)
print(ac3)
print(si3)

[1 0 0 ... 1 0 1]
0.8272345530893821
0.14083893771529316
